name = "fluo"
version = "1.0.0"
licences = ["MIT"]
repository = { type = "github", user = "nablaFox", repo = "Fluo" }
description = "Simple and elegant vulkan renderer"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
